Diagnoses crud
iTechArt-RubyLab/medical-center pull request #21
Opened 2022-01-31 08:10 UTC by PandaGrom

# Description

[CRUD for Diagnosis](https://trello.com/c/7LYhQQlf/53-crud-for-diagnoses)

## Type of change

- [ ] Bug fix
- [ ] New feature 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-31 09:13 UTC, hannazspot requested changes
pls add me in reviewers, thanks

2022-01-31 09:13 UTC, hannazspot commented on app/api/v1/admin/diagnoses.rb
> +            diagnosis
```
Diagnosis.find(params[:id]).tap do |diagnosis|
  diagnosis.update!(params)
end
```

pls read about methods with a bang and what's the difference between `update` & `update!` and about `.tap`

2022-01-31 09:13 UTC, hannazspot commented on app/api/v1/admin/diagnoses.rb
> +      # end
remove comments pls

2022-01-31 09:13 UTC, hannazspot commented on app/api/v1/diagnoses.rb
> +  class Diagnoses < API
why is a model's name in a plural form?

2022-02-01 07:59 UTC, hannazspot commented on spec/api/v1/admin/diagnoses_spec.rb
> +  describe 'POST' do
`POST` is not accurate enough in that context, you can have a couple of handlers that manage post queries, so this description doesn't suit here

2022-02-01 08:36 UTC, hannazspot approved these changes

2022-02-01 08:43 UTC, alhimick-prog approved these changes

2022-02-01 08:43 UTC, merged