Added sidekiq & sidekiq-cron, mailer to notice patient/doctor
iTechArt-RubyLab/medical-center pull request #26
Opened 2022-02-03 17:44 UTC by AndrewTehan

# Description

[Email Notifications about Appointments](https://trello.com/c/BKMYnKx7)
## Type of change

- [ ] Bug fix
- [ ] New feature 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-06 22:12 UTC, PandaGrom commented on config/initializers/sidekiq.rb
> +end
add missing line

2022-02-07 08:32 UTC, hannazspot requested changes

2022-02-07 08:32 UTC, hannazspot commented on Gemfile
> +gem "sidekiq", '~> 6.3.1'
`""`

2022-02-07 08:32 UTC, hannazspot commented on app/mailers/user_mailer.rb
> +    @visit_cabinet = params[:visit_cabinet]
`visit_room` is more suitable here

2022-02-07 08:32 UTC, hannazspot commented on app/workers/notification_worker.rb
> +                      host: host).appointment_notification.deliver_now
do you find code duplication, don't you?

2022-02-07 08:32 UTC, hannazspot commented on config/routes.rb
> +  mount Sidekiq::Web => '/sidekiq'
does anybody have access to the route? 

Could you pls add basic authentication there? only for developers, cause only devs use this tool

2022-02-08 06:47 UTC, nieisnuje commented on config/routes.rb
> +  end
https://github.com/mperham/sidekiq/wiki/Monitoring#authentication

2022-02-08 06:48 UTC, nieisnuje commented on config/routes.rb
> +  end
You should be able to use sidekiq not only in development

2022-02-08 06:50 UTC, nieisnuje commented on config/initializers/sidekiq.rb
> +  config.redis = { url: 'redis://localhost:6379/' }
You can put `redis://localhost:6379/` into env variables 
It will give you the ability to use different URLs depending on the environment

2022-02-08 06:51 UTC, nieisnuje commented on config/initializers/sidekiq.rb
> +  config.redis = { url: 'redis://localhost:6379/' }
Read more here https://railshero.pw/489/all-about-heroku-environment-variables/ if you haven't use env variables yet

2022-02-08 11:50 UTC, alhimick-prog approved these changes

2022-02-08 12:22 UTC, hannazspot approved these changes

2022-02-08 12:23 UTC, merged