Error handling
iTechArt-RubyLab/medical-center pull request #28
Opened 2022-02-06 15:11 UTC by PandaGrom

# Description
[Add error handling for CRUD operations](https://trello.com/c/wGRbj1hx/70-add-error-handling-for-crud-operations)
## Type of change

- [ ] Bug fix
- [ ] New feature 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-02-07 08:26 UTC, hannazspot requested changes
The tests are supposed to be written when you add new logic

2022-02-07 08:26 UTC, hannazspot commented on app/api/api.rb
> +  ].freeze
could you pls review how to skip callbacks in controllers directly, but not in a general one:

there're some `skip_*` callbacks in rails => [documentation](https://api.rubyonrails.org/v6.1.4/classes/AbstractController/Callbacks/ClassMethods.html)

2022-02-07 08:26 UTC, hannazspot commented on app/api/error_handler.rb
> +    rescue StandardError => e
I'd not catch all errors thru StandardError, it's too general. We'll lose visibility about errors that happen in our application.

So, I'd recommend catching exact errors: ActiveRecord::RecordNotFound, ActionController::ParameterMissing, ActiveModel::ValidationError

2022-02-07 08:26 UTC, hannazspot commented on app/api/error_handler.rb
> +      throw :error, message: e.message || options[:default_message], status: 500
could you please read about errors and why have to avoid raising 500 errors on our own

2022-02-08 11:50 UTC, alhimick-prog approved these changes

2022-02-08 13:10 UTC, hannazspot approved these changes

2022-02-08 13:33 UTC, merged